/******************************************************************************
 *
 * Module: ICU
 *
 * File Name: icu.c
 *
 * Description: Source file for the AVR ICU driver
 *
 * Author: Saber Mahmoud
 *
 *******************************************************************************/
#include"gpio.h"
#include"ultrasonic.h"
#include"icu.h"
#include<util/delay.h>
#include"common_macros.h"
#include<avr/io.h>
#include<math.h>
uint8 g_edgecount=0;
void (*g_callBackaddressPtr)(void)=Ultrasonic_edgeProcessing;
/*
• Description
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the
GPIO driver.
• Inputs: None
• Return: None

 */
void Ultrasonic_init(void)
{
	Icu_ConfigType config_ptr={F_CPU_8,RISING};
	Icu_init(&config_ptr);			/*the clock now is fcpu/8 and the icu triggers rising edge*/
	Icu_setCallBack(g_callBackaddressPtr);
	GPIO_setupPinDirection(PORTB_ID, PIN5_ID, PIN_OUTPUT); /*set PB5 (trigger pin) as output*/

}
/*
• Description
➢ Send the Trigger pulse to the ultrasonic.
• Inputs: None
• Return: None
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_LOW);
}
/*
• Description
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment.
• Inputs: None
• Return: The measured distance in Centimeter.
*/
uint16 Ultrasonic_readDistance(void)
{
	Ultrasonic_Trigger();
	while(g_edgecount!=2);
	g_edgecount=0;
	uint16 time=Icu_getInputCaptureValue();
	uint16 distance=(uint16)(time*0.01725+1);
	return distance;
}
/*
• Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.
• Inputs: None
• Return: None
 *
 */
void Ultrasonic_edgeProcessing()
{
	g_edgecount++;
	if(g_edgecount==1)
	{
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgecount==2)
	{
		Icu_setEdgeDetectionType(RISING);
	}
}
